name: simple-retention-model
channels:
  - conda-forge
  - defaults
dependencies:
  - lifelines
  - matplotlib-base
  - numpy
  - pandas
  - pip
  - python
  - python-dateutil
  - pip:
    - streamlit-aggrid