name: simple-retention-model
channels:
  - conda-forge
  - defaults
dependencies:
  - lifelines
  - matplotlib-base
  - numpy
  - pandas
  - pip=22.3
  - python=3.9
  - python-dateutil
  - pip:
    - streamlit==1.13.0gi
    - streamlit-aggrid